version: '3.1'
services:
  db:
    hostname: mysql
    image: mysql:8.0.23
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"

volumes:
  db_data: