spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: &connectionUrl jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3306}/${DB_CONNECTION_NAME:e-library-db}?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: &username ${DB_CONNECTION_USERNAME:root}
    password: &password ${DB_CONNECTION_PASSWORD:12345}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwtProperties:
    secret: ZFcxcGFXUnBkVzFwYVdScGRXMXBhV1JwZFcxcGFXUnBkVzFwYVdScGRXMXBhV1JwZFcxcGFXUnBkVzFwYVdScGRXMXBhV1JwZFcxcGFXUnA=
    token-validity-in-seconds: 300           # 5 minute